
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 23 20:28:17 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 23;
  public static final int Double = 10;
  public static final int Llave_c = 30;
  public static final int Op_booleano = 26;
  public static final int Llave_a = 29;
  public static final int CHAR = 8;
  public static final int If = 12;
  public static final int Void = 36;
  public static final int T_dato = 6;
  public static final int Else = 13;
  public static final int Corchete_c = 32;
  public static final int Corchete_a = 31;
  public static final int Punto = 39;
  public static final int While = 15;
  public static final int Division = 21;
  public static final int Int = 7;
  public static final int Flotante = 9;
  public static final int Cadena = 11;
  public static final int Parentesis_c = 28;
  public static final int Parentesis_a = 27;
  public static final int For = 16;
  public static final int EOF = 0;
  public static final int P_coma = 34;
  public static final int Printf = 5;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int punto = 38;
  public static final int Op_atribucion = 24;
  public static final int ERROR = 41;
  public static final int Do = 14;
  public static final int Op_logico = 22;
  public static final int ComillasSimples = 4;
  public static final int Identificador = 35;
  public static final int Resta = 19;
  public static final int Multiplicacion = 20;
  public static final int Op_incremento = 25;
  public static final int Numero = 40;
  public static final int Suma = 18;
  public static final int Main = 33;
  public static final int Igual = 17;
  public static final int Comi = 37;
  public static final int Comillas = 3;
}

